// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserUserGroupPublicResponse user user group public response
//
// swagger:model userUserGroupPublicResponse
type UserUserGroupPublicResponse struct {

	// avatar
	Avatar string `json:"avatar,omitempty"`

	// banner
	Banner string `json:"banner,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// display name
	DisplayName string `json:"displayName,omitempty"`

	// followers
	Followers []string `json:"followers"`

	// repeated RelatedUserGroup recommended_artists = 17;
	// map<string, string> publisher = 21;
	// map<string, string> pro = 22;
	GroupEmail string `json:"groupEmail,omitempty"`

	// group type
	GroupType string `json:"groupType,omitempty"`

	// links
	Links []string `json:"links"`

	// member of groups
	MemberOfGroups []string `json:"memberOfGroups"`

	// members
	Members []string `json:"members"`

	// short bio
	ShortBio string `json:"shortBio,omitempty"`

	// tags
	Tags []string `json:"tags"`
}

// Validate validates this user user group public response
func (m *UserUserGroupPublicResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user user group public response based on context it is used
func (m *UserUserGroupPublicResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserUserGroupPublicResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserUserGroupPublicResponse) UnmarshalBinary(b []byte) error {
	var res UserUserGroupPublicResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
